### ISSUE TITLE
flatpak

### ISSUE THREAD

**Issue by corebots** [dcharles525/crypt#27]
Hi is it possible to install Crypt on Fedora? If so, do you have any instructions please and could you consider adding it to Flathub? Thanks!

Also, what are your plans with the app, can you share a roadmap perhaps?

(just happy to see an actual app for crypto prices and charts ;)

**Comment by dcharles525** [comment]
Hi @corebots with Elementary moving to flatpaks there will be one! I have no idea how to do that stuff yet, but currently I am getting coin customization, limit notifications, prediction charts, more charts in general, and some other tweaks into the software (This is just all I have on my roadmap at the moment).

I would love to add it to Flathub and other app repos soon, just gotta figure it all out since I am pretty new to the Linux software space. I will keep you updated!

**Comment by corebots** [comment]
nice to hear that, thanks ;)

**Comment by dcharles525** [comment]
Whew! This is going out as Flatpak on the Appcenter very soon.
